version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_HOST=http://localhost:3000

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile-api
    volumes:
      - ./backend:/app
    depends_on:
      - background_jobs
      - postgres
      - redis_sidekiq
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq

  background_jobs:
    build:
      context: ./backend
      dockerfile: Dockerfile-background_jobs
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis_sidekiq
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq

  postgres:
    image: postgres:12.0
    volumes:
      - './backend/.docker-volumes/postgres:/var/lib/postgresql/data'

  redis_sidekiq:
    image: redis:5.0
    volumes:
      - './backend/.docker-volumes/redis_sidekiq:/data'
