require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  IndentOneStep: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  AllowedNames:
    - '_'

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never


Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/MultilineBlockChain:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/RegexpLiteral:
  EnforcedStyle: slashes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
