version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - .:/app
    depends_on:
      - background_jobs
      - postgres
      - redis_sidekiq
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq

  background_jobs:
    build:
      context: .
      dockerfile: Dockerfile-background_jobs
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis_sidekiq
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq

  postgres:
    image: postgres:12.0
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis_sidekiq:
    image: redis:5.0
    volumes:
      - 'redis:/data'

volumes:
  postgres:
  redis:
