source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'activerecord-import'
gem 'bootsnap', '~> 1.4.5', require: false
gem 'dry-matcher'
gem 'dry-monads'
gem 'dry-struct'
gem 'dry-system'
gem 'dry-types'
gem 'faraday'
gem 'faraday_middleware'
gem 'foreman'
gem 'jbuilder', '~> 2.5'
gem 'pg'
gem 'puma', '~> 4.3.3'
gem 'rack', '2.0.8'
gem 'rack-cors'
gem 'rails', '~> 5.2.3'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-unique-jobs'

group :development, :test do
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-remote'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'database_cleaner', '1.8.0.beta'
  gem 'vcr'
  gem 'webmock'
end
