version: '3'
services:
  web:
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis_sidekiq
    volumes:
      - .:/myapp

  sidekiq:
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/cr-clan-monitor
      - REDIS_SIDEKIQ_URL=redis://redis_sidekiq
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis_sidekiq
    volumes:
      - .:/myapp

  postgres:
    image: postgres:12.0
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis_sidekiq:
    image: redis:5.0
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
